/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportsinventory;

import java.util.*;

/**
 *
 * @author User
 */
public class SportsInventoryUI extends javax.swing.JFrame {

    ArrayList<String> balls = new ArrayList();
    ArrayList<String> caps = new ArrayList();
    ArrayList<String> Bats = new ArrayList();
    ArrayList<String> safetyWear = new ArrayList();
    ArrayList<String> clothes = new ArrayList();
    ArrayList<String> shoes = new ArrayList();

    /**
     * Creates new form SportsInventoryUI
     */
    public SportsInventoryUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        numPrompt = new javax.swing.JLabel();
        typesOfInvLabel = new javax.swing.JLabel();
        ballsLabel = new javax.swing.JLabel();
        capsLabel = new javax.swing.JLabel();
        safetyWearLabel = new javax.swing.JLabel();
        shoesLabel = new javax.swing.JLabel();
        batsLabel = new javax.swing.JLabel();
        typeOfInvInput = new javax.swing.JTextField();
        clothesLabel1 = new javax.swing.JLabel();
        typePrompt1 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        outputPane = new javax.swing.JScrollPane();
        outputLabel = new javax.swing.JTextArea();
        showInvButton = new javax.swing.JButton();
        numOfInvInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        title.setText("Sports Inventory");
        getContentPane().add(title);
        title.setBounds(20, 20, 340, 60);

        numPrompt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numPrompt.setText("Number:");
        getContentPane().add(numPrompt);
        numPrompt.setBounds(120, 150, 70, 22);

        typesOfInvLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typesOfInvLabel.setText("Types of Inventory:");
        typesOfInvLabel.setToolTipText("");
        getContentPane().add(typesOfInvLabel);
        typesOfInvLabel.setBounds(370, 30, 190, 20);

        ballsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ballsLabel.setText("Balls ");
        getContentPane().add(ballsLabel);
        ballsLabel.setBounds(400, 50, 70, 22);

        capsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        capsLabel.setText("Caps");
        getContentPane().add(capsLabel);
        capsLabel.setBounds(400, 130, 110, 22);

        safetyWearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        safetyWearLabel.setText("Safety Wear");
        getContentPane().add(safetyWearLabel);
        safetyWearLabel.setBounds(400, 90, 110, 22);

        shoesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shoesLabel.setText("Shoes");
        getContentPane().add(shoesLabel);
        shoesLabel.setBounds(400, 110, 110, 22);

        batsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        batsLabel.setText("Bats");
        getContentPane().add(batsLabel);
        batsLabel.setBounds(400, 150, 110, 22);
        getContentPane().add(typeOfInvInput);
        typeOfInvInput.setBounds(210, 110, 140, 30);

        clothesLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clothesLabel1.setText("Clothes");
        getContentPane().add(clothesLabel1);
        clothesLabel1.setBounds(400, 70, 70, 22);

        typePrompt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typePrompt1.setText("Type:");
        getContentPane().add(typePrompt1);
        typePrompt1.setBounds(120, 110, 70, 22);

        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeButton);
        removeButton.setBounds(300, 190, 110, 23);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(120, 190, 90, 23);

        outputLabel.setEditable(false);
        outputLabel.setColumns(20);
        outputLabel.setLineWrap(true);
        outputLabel.setRows(5);
        outputLabel.setWrapStyleWord(true);
        outputPane.setViewportView(outputLabel);

        getContentPane().add(outputPane);
        outputPane.setBounds(10, 250, 340, 250);

        showInvButton.setText("SHOW INVENTORY");
        showInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInvButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showInvButton);
        showInvButton.setBounds(360, 260, 150, 23);
        getContentPane().add(numOfInvInput);
        numOfInvInput.setBounds(210, 140, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 80, 70, 30);

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        getContentPane().add(nameInput);
        nameInput.setBounds(210, 80, 140, 30);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsinventory/sportsball_wallpaperpattern_1500_2048x.jpg"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(-150, -180, 910, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInvButtonActionPerformed

        int numOfBalls, numOfBats, numOfCaps, numOfSafety, numOfShoes, numOfClothes;

        numOfBalls = balls.size();
        numOfCaps = caps.size();
        numOfBats = Bats.size();
        numOfSafety = safetyWear.size();
        numOfShoes = shoes.size();
        numOfClothes = clothes.size();
        

        outputLabel.setText("Number of Balls: " + numOfBalls
                + "\nNumber of Bats: " + numOfBats + "\nNumber of Caps: " + numOfCaps + "\nNumber of Safety Wear Items: " + numOfSafety + "\nNumber of Shoes: "
                + numOfShoes + "\nNumber of Clothes: " + numOfClothes);
        
        for (int i=0; i<balls.size(); i++)
            outputLabel.setText(outputLabel.getText() + "\n" + i + ": " + balls.get(i));

    }//GEN-LAST:event_showInvButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String type;
        int number;

        number = Integer.parseInt(numOfInvInput.getText());
        type = typeOfInvInput.getText();

        switch (type) {
            case "Balls":
            case "balls":
                outputLabel.setText(number + " Balls Added");
                ballsAdded();
                break;
            case "Bats":
            case "bats":
                outputLabel.setText(number + " Bats Added");
                batsAdded();
                break;
            case "Shoes":
            case "shoes":
                outputLabel.setText(number + " Shoes Added");
                shoesAdded();
                break;
            case "Clothes":
            case "clothes":
                outputLabel.setText(number + " Clothes Added");
                clothesAdded();
                break;
            case "caps":
            case "Caps":
                outputLabel.setText(number + " Caps Added");
                capsAdded();
                break;
            case "Safety":
            case "safety":
            case "safety wear":
            case "Safety Wear":
                outputLabel.setText(number + " Safety Wear Added");
                safetyAdded();
                break;
            default:
                outputLabel.setText("Error");
                break;
        }


    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String type, name;

        int number;
        number = Integer.parseInt(numOfInvInput.getText());

        type = typeOfInvInput.getText();
        name = nameInput.getText();
        
        
        switch (type){
            case "Balls":
            case "balls":
                outputLabel.setText(number + " Balls Removed");
                ballsRemoved();
                break;
            case "Bats":
            case "bats":
                outputLabel.setText(number + " Bats Removed");
                batsRemoved();
                break;
            case "Shoes":
            case "shoes":
                outputLabel.setText(number + " Shoes Removed");
                shoesRemoved();
                break;
            case "Clothes":
            case "clothes":
                outputLabel.setText(number + " Clothes Removed");
                clothesRemoved();
                break;
            case "caps":
            case "Caps":
                outputLabel.setText(number + "Caps Removed");
                capsRemoved();
                break;
            case "Safety":
            case "safety":
            case "safety wear":
            case "Safety Wear":
                outputLabel.setText(number + " Safety Wear Removed");
                safetyRemoved();
                break;
            default:
                outputLabel.setText("Error");
                break;
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void ballsAdded() {
        String name;
        int number;
        number = Integer.parseInt(numOfInvInput.getText());
        name = nameInput.getText();

        for (int i = 0; i < number; i++) {
            balls.add(name);
        }
    }

    private void ballsRemoved() {
        int number;
        number = Integer.parseInt(numOfInvInput.getText());

        for (int c = 0; c < number; c++) {
            balls.remove(balls.size() - 1);
        }
    }

    private void capsAdded() {
        int number;
        String name;
        number = Integer.parseInt(typeOfInvInput.getText());
        name = nameInput.getText();

        for (int i = 0; i < number; i++) {
            caps.add(name);
        }
    }

    private void capsRemoved() {
        int number;
        number = Integer.parseInt(numOfInvInput.getText());

        for (int i = 0; i < number; i++) {
            caps.remove(caps.size() - 1);
        }
    }

    private void shoesAdded() {
        int number;
        String shoename;
        number = Integer.parseInt(typeOfInvInput.getText());
        shoename = nameInput.getText();

        for (int i = 0; i < number; i++) {
            shoes.add(shoename);

        }
    }

    private void shoesRemoved() {
        int number;
        number = Integer.parseInt(numOfInvInput.getText());

        for (int i = 0; i < number; i++) {
            shoes.remove(shoes.size() - 1);
        }
    }

    private void clothesAdded() {
        int number;
        String clothName;
        number = Integer.parseInt(typeOfInvInput.getText());
        clothName= nameInput.getText();

        for (int i = 0; i < number; i++) {
            clothes.add(clothName);

        }
    }

    private void clothesRemoved() {
        int number;
        number = Integer.parseInt(numOfInvInput.getText());

        for (int i = 0; i < number; i++) {
            clothes.remove(clothes.size() - 1);
        }
    }

    private void safetyAdded() {
        int number;
        String safetyName;
        number = Integer.parseInt(numOfInvInput.getText());
        safetyName = nameInput.getText();

        for (int i = 0; i < number; i++) {
            safetyWear.add(safetyName);
        }
    }

    private void safetyRemoved() {
        int number;
        number = Integer.parseInt(numOfInvInput.getText());

        for (int i = 0; i < number; i++) {
            safetyWear.remove(nameInput.getText());
        }
    }

    private void batsAdded() {
        int number;
        String batName;
        number = Integer.parseInt(typeOfInvInput.getText());
        batName = nameInput.getText();

        for (int i = 0; i < number; i++) {
            Bats.add(batName);

        }
    }

    private void batsRemoved() {
        int number;
        number = Integer.parseInt(numOfInvInput.getText());

        for (int i = 0; i < number; i++) {
            Bats.remove(Bats.size() - 1);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SportsInventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SportsInventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SportsInventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SportsInventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SportsInventoryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel ballsLabel;
    private javax.swing.JLabel batsLabel;
    private javax.swing.JLabel capsLabel;
    private javax.swing.JLabel clothesLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField numOfInvInput;
    private javax.swing.JLabel numPrompt;
    private javax.swing.JTextArea outputLabel;
    private javax.swing.JScrollPane outputPane;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel safetyWearLabel;
    private javax.swing.JLabel shoesLabel;
    private javax.swing.JButton showInvButton;
    private javax.swing.JLabel title;
    private javax.swing.JTextField typeOfInvInput;
    private javax.swing.JLabel typePrompt1;
    private javax.swing.JLabel typesOfInvLabel;
    // End of variables declaration//GEN-END:variables
}
